# Generated by Django 6.0.6 on 2026-07-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('natural_language_prompt', models.TextField()),
                ('regex_pattern', models.TextField(blank=True)),
                ('replacement_value', models.CharField(max_length=255)),
                ('target_column', models.CharField(max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
